// AUTOGENERATED! DO NOT EDIT.
package accountingV2Client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"io"
	"tonky/holistic/domain/foodStore"
	"BasicGoImport(): undefined"
	"tonky/holistic/clients"
	svc "tonky/holistic/services/accountingV2"
)

type IAccountingV2Client interface {
	GetOrderByID(context.Context, svc.OrderID) (svc.Order, error)
	CreateOrder(context.Context, svc.NewFoodOrder) (svc.Order, error)
}

func New(config clients.Config) AccountingV2Client {
	return AccountingV2Client{
		config: config,
	}
}

func NewFromEnv(env string) AccountingV2Client {
	svcConf := svc.MustEnvConfig()

	envConf := clients.ConfigForEnv("accountingV2", env)
	envConf.Port = svcConf.Port

	return AccountingV2Client{
		config: envConf,
	}
}

type AccountingV2Client struct {
	config clients.Config
}

func (c AccountingV2Client) GetOrderByID(ctx context.Context, arg svc.OrderID) (svc.Order, error) {
	var reply svc.Order

	jsonBody, err := json.Marshal(arg)
	if err != nil { return reply, err}

	bodyReader := bytes.NewReader(jsonBody)

 	requestURL := fmt.Sprintf("%s/%s", c.config.ServerAddress(), "GetOrderByIDGetOrderByID")

 	req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
	if err != nil { return reply, err }

	res, err := http.DefaultClient.Do(req)
	if err != nil { return reply, err }

	resBody, err := io.ReadAll(res.Body)
	if err != nil { return reply, err }

	if err := json.Unmarshal(resBody, &reply); err != nil { return reply, err }

	return reply, nil
}

func (c AccountingV2Client) CreateOrder(ctx context.Context, arg svc.NewFoodOrder) (svc.Order, error) {
	var reply svc.Order

	jsonBody, err := json.Marshal(arg)
	if err != nil { return reply, err}

	bodyReader := bytes.NewReader(jsonBody)

 	requestURL := fmt.Sprintf("%s/%s", c.config.ServerAddress(), "CreateOrderCreateOrder")

 	req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
	if err != nil { return reply, err }

	res, err := http.DefaultClient.Do(req)
	if err != nil { return reply, err }

	resBody, err := io.ReadAll(res.Body)
	if err != nil { return reply, err }

	if err := json.Unmarshal(resBody, &reply); err != nil { return reply, err }

	return reply, nil
}

