// AUTOGENERATED! DO NOT EDIT.

package shipping

import (
	"context"
	"tonky/holistic/infra/kafkaProducer"
	"tonky/holistic/infra/kafkaConsumer"
	"tonky/holistic/infra/logger"
)

type Deps struct {
	Config Config
	Logger *logger.Slog
    OrdererRepo OrdererRepository
    ShippingOrderShippedProducer kafkaProducer.IShippingOrderShipped
    AccountingOrderPaidConsumer kafkaConsumer.IAccountingOrderPaid
}


type App struct {
	Deps		Deps
	Logger		*logger.Slog
}

func NewApp(deps Deps) (App, error) {
	if deps.Logger == nil {
		deps.Logger = &logger.Slog{}
	}

	app := App{
		Deps:       deps,
		Logger:     deps.Logger,
	}

	return app, nil
}

func (a App) RunConsumers() {
	a.Logger.Info(">> shipping.App.RunConsumers()")

	ctx := context.Background()

	go func() {
		for err := range a.Deps.AccountingOrderPaidConsumer.Run(ctx, a.AccountingOrderPaidProcessor) {
			a.Logger.Warn(err.Error())
		}
	}()
}
