// AUTOGENERATED! DO NOT EDIT.
package pricing

import (
	"context"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/postgres"
	"tonky/holistic/domain/food"
	"tonky/holistic/domain/pricing"
)

type OrdererRepository interface {
    ReadOrderPricingByID(context.Context, food.OrderID) (pricing.OrderPrice, error)
}

type PostgresOrderer struct {
	logger logger.Slog
	client postgres.Client
}

func NewPostgresOrderer(logger logger.Slog, conf postgres.Config) (*PostgresOrderer, error) {
	client, err := postgres.NewClient(conf)
	if err != nil {
		return nil, err
	}

	return &PostgresOrderer{
		logger: logger,
		client: client,
	}, nil
}
