// AUTOGENERATED! DO NOT EDIT.
package pricing

import (
	"tonky/holistic/infra/postgres"

	"github.com/kelseyhightower/envconfig"
)

// app specific config - infra, flags etc
type Config struct {
	Environment   string `default:"dev"`

    PostgresOrderer postgres.Config

}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("pricing", &c)
}
