// AUTOGENERATED! DO NOT EDIT.
package clients


import (
	"context"
	"log"
	"net/rpc"
	"tonky/holistic/domain/food"
    // generate imports
)

func NewPizzeria(config Config) PizzeriaClient {
	return PizzeriaClient{
		config: config,
	}
}

type PizzeriaClient struct {
	config Config
}

func (c PizzeriaClient) ReadOrder(ctx context.Context, req food.OrderID) (food.Order, error) {
	client, err := rpc.DialHTTP("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply food.Order

	err = client.Call("Pizzeria.ReadOrder", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

func (c PizzeriaClient) CreateOrder(ctx context.Context, req food.Order) (food.Order, error) {
	client, err := rpc.DialHTTP("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply food.Order

	err = client.Call("Pizzeria.CreateOrder", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

