// AUTOGENERATED! DO NOT EDIT.
package shipping

import (
	app "tonky/holistic/apps/shipping"
	"github.com/kelseyhightower/envconfig"
	"github.com/samber/do/v2"
)

// service specific config - env, secrets, run mode, flags etc
type Config struct {
	Environment   string `default:"dev"`
	Port int `default:"1234"`

	App app.Config

}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("shipping", &c)
}

func NewConfig(i do.Injector) (*Config, error) {
	config, err := NewEnvConfig()
	if err != nil {
		return nil, err
	}

	return &config, nil
}
