// AUTOGENERATED! DO NOT EDIT.
package accountingV2

import (
	"context"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/postgres"
	"tonky/holistic/domain/foodStore"
	"tonky/holistic/apps/accountingV2"
)

var _ IFoodOrderer = new(FoodOrderer)

type IFoodOrderer interface {
    GetOrderByID(context.Context, foodStore.OrderID) (foodStore.Order, error)
    SaveNewOrder(context.Context, accountingV2.NewFoodOrder) (foodStore.Order, error)
}

type FoodOrderer struct {
	logger logger.Slog
	client postgres.Client
}

func NewFoodOrderer(logger logger.Slog, conf postgres.Config) (*FoodOrderer, error) {
	client, err := postgres.NewClient(conf)
	if err != nil {
		return nil, err
	}

	return &FoodOrderer{
		logger: logger,
		client: client,
	}, nil
}
