// AUTOGENERATED! DO NOT EDIT.
package accountingV2

import (
    "log/slog"
	"tonky/holistic/infra/kafka"

	"tonky/holistic/infra/postgres"
    
	"github.com/kelseyhightower/envconfig"
)

// app specific config - infra, flags etc
type Config struct {
	Environment   string `default:"dev"`

    Kafka kafka.Config

    FoodOrderer postgres.Config
    KafkaConsumptionRPSLimit int `split_words:"false"`
}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("accountingV2", &c)
}

func MustEnvConfig() Config {
	var c Config

	if err := envconfig.Process("accountingV2_app", &c); err != nil {
        slog.Error("MustEnvConfig error for accountingV2", slog.Any("Process() error", err))
        panic(err)
    }

	return c
}
