// AUTOGENERATED! DO NOT EDIT.
package pizzeriaClient


import (
	"context"
	"log"
	"net/rpc"
	"tonky/holistic/clients"
	 "tonky/holistic/domain/food"
	svc "tonky/holistic/services/pizzeria"
)

type IPizzeriaClient interface {
	ReadOrder(context.Context, food.OrderID) (food.Order, error)
	CreateOrder(context.Context, svc.NewOrder) (food.Order, error)
	UpdateOrder(context.Context, svc.UpdateOrder) (food.Order, error)
}

func New(config clients.Config) PizzeriaClient {
	return PizzeriaClient{
		config: config,
	}
}

type PizzeriaClient struct {
	config clients.Config
}

func (c PizzeriaClient) ReadOrder(ctx context.Context, req food.OrderID) (food.Order, error) {
	client, err := rpc.Dial("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply food.Order

	err = client.Call("Pizzeria.ReadOrder", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

func (c PizzeriaClient) CreateOrder(ctx context.Context, req svc.NewOrder) (food.Order, error) {
	client, err := rpc.Dial("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply food.Order

	err = client.Call("Pizzeria.CreateOrder", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

func (c PizzeriaClient) UpdateOrder(ctx context.Context, req svc.UpdateOrder) (food.Order, error) {
	client, err := rpc.Dial("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply food.Order

	err = client.Call("Pizzeria.UpdateOrder", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

