// AUTOGENERATED! DO NOT EDIT.
package legacyClient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"io"
	"tonky/holistic/clients"
	svc "tonky/holistic/services/legacy"
	 "tonky/holistic/domain/food"
)

type ILegacyClient interface {
	ReadOrder(context.Context, svc.OrderID) (food.Order, error)
	CreateOrder(context.Context, svc.NewOrder) (food.Order, error)
	UpdateOrder(context.Context, svc.UpdateOrder) (food.Order, error)
}

func New(config clients.Config) LegacyClient {
	return LegacyClient{
		config: config,
	}
}

type LegacyClient struct {
	config clients.Config
}

func (c LegacyClient) ReadOrder(ctx context.Context, arg svc.OrderID) (food.Order, error) {
	var reply food.Order

	jsonBody, err := json.Marshal(arg)
	if err != nil { return reply, err}

	bodyReader := bytes.NewReader(jsonBody)

 	requestURL := fmt.Sprintf("%s/%s", c.config.ServerAddress(), "GetOrder")

 	req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
	if err != nil { return reply, err }

	res, err := http.DefaultClient.Do(req)
	if err != nil { return reply, err }

	resBody, err := io.ReadAll(res.Body)
	if err != nil { return reply, err }

	if err := json.Unmarshal(resBody, &reply); err != nil { return reply, err }

	return reply, nil
}

func (c LegacyClient) CreateOrder(ctx context.Context, arg svc.NewOrder) (food.Order, error) {
	var reply food.Order

	jsonBody, err := json.Marshal(arg)
	if err != nil { return reply, err}

	bodyReader := bytes.NewReader(jsonBody)

 	requestURL := fmt.Sprintf("%s/%s", c.config.ServerAddress(), "PostOrder")

 	req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
	if err != nil { return reply, err }

	res, err := http.DefaultClient.Do(req)
	if err != nil { return reply, err }

	resBody, err := io.ReadAll(res.Body)
	if err != nil { return reply, err }

	if err := json.Unmarshal(resBody, &reply); err != nil { return reply, err }

	return reply, nil
}

func (c LegacyClient) UpdateOrder(ctx context.Context, arg svc.UpdateOrder) (food.Order, error) {
	var reply food.Order

	jsonBody, err := json.Marshal(arg)
	if err != nil { return reply, err}

	bodyReader := bytes.NewReader(jsonBody)

 	requestURL := fmt.Sprintf("%s/%s", c.config.ServerAddress(), "PutOrder")

 	req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
	if err != nil { return reply, err }

	res, err := http.DefaultClient.Do(req)
	if err != nil { return reply, err }

	resBody, err := io.ReadAll(res.Body)
	if err != nil { return reply, err }

	if err := json.Unmarshal(resBody, &reply); err != nil { return reply, err }

	return reply, nil
}

