// AUTOGENERATED! DO NOT EDIT.
package pricingClient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"io"
	"tonky/holistic/clients"
	svc "tonky/holistic/services/pricing"
	 "tonky/holistic/domain/pricing"
)

type IPricingClient interface {
	ReadOrder(context.Context, svc.OrderID) (pricing.OrderPrice, error)
}

func New(config clients.Config) PricingClient {
	return PricingClient{
		config: config,
	}
}

type PricingClient struct {
	config clients.Config
}

func (c PricingClient) ReadOrder(ctx context.Context, arg svc.OrderID) (pricing.OrderPrice, error) {
	var reply pricing.OrderPrice

	jsonBody, err := json.Marshal(arg)
	if err != nil { return reply, err}

	bodyReader := bytes.NewReader(jsonBody)

 	requestURL := fmt.Sprintf("%s/%s", c.config.ServerAddress(), "GetOrder")

 	req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
	if err != nil { return reply, err }

	res, err := http.DefaultClient.Do(req)
	if err != nil { return reply, err }

	resBody, err := io.ReadAll(res.Body)
	if err != nil { return reply, err }

	if err := json.Unmarshal(resBody, &reply); err != nil { return reply, err }

	return reply, nil
}

