// AUTOGENERATED! DO NOT EDIT.
package accountingClient


import (
	"context"
	"log"
	"net/rpc"
	"tonky/holistic/clients"
	 "tonky/holistic/domain/food"
	 "tonky/holistic/domain/accounting"
)

type IAccountingClient interface {
	ReadOrder(context.Context, food.OrderID) (accounting.Order, error)
}

func New(config clients.Config) AccountingClient {
	return AccountingClient{
		config: config,
	}
}

type AccountingClient struct {
	config clients.Config
}

func (c AccountingClient) ReadOrder(ctx context.Context, req food.OrderID) (accounting.Order, error) {
	client, err := rpc.Dial("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply accounting.Order

	err = client.Call("Accounting.ReadOrder", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

