// AUTOGENERATED! DO NOT EDIT.
package pizzeria

import (
	"context"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/kafka"
	"tonky/holistic/infra/kafkaProducer"

	 "tonky/holistic/domain/food"
)

// compile-time check to make sure app-level interface is implemented
var _ FoodOrderProducer = new(KafkaFoodOrderProducer) 

type FoodOrderProducer interface {
	ProduceFoodOrder(context.Context, food.Order) error
	ProduceFoodOrderBatch(context.Context, []food.Order) error
}

type KafkaFoodOrderProducer struct {
	logger logger.Slog
	client kafkaProducer.IProducer
}

func NewKafkaFoodOrderProducer(logger logger.Slog, config kafka.Config) (*KafkaFoodOrderProducer, error) {
	client := kafkaProducer.NewProducer(config, "pizzeria.order")

	return &KafkaFoodOrderProducer{
		logger: logger,
		client: client,
	}, nil
}
