// AUTOGENERATED! DO NOT EDIT.
package pizzeria

import (
	"tonky/holistic/infra/kafka"
	"tonky/holistic/infra/postgres"

	"github.com/kelseyhightower/envconfig"
)

// app specific config - dependencies, runtime etc
type Config struct {
	Environment   string `default:"dev"`

    Kafka kafka.Config
    PostgresOrderer postgres.Config

    EnabledInRegions []string `split_words:"true"`
}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("pizzeria", &c)
}
