// AUTOGENERATED! DO NOT EDIT.
package pizzeria

import (
	"context"
	"tonky/holistic/domain/food"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/kafkaProducer"
)

type FoodOrderProducer interface {
	ProduceFoodOrder(context.Context, food.Order) error
	ProduceFoodOrderBatch(context.Context, []food.Order) error
}

type KafkaFoodOrderProducer struct {
	logger logger.Slog
	client kafkaProducer.IProducer
}

func NewKafkaFoodOrderProducer(logger logger.Slog, config kafkaProducer.Config) (*KafkaFoodOrderProducer, error) {
	client := kafkaProducer.NewProducer(config, "pizzeria.order")

	return &KafkaFoodOrderProducer{
		logger: logger,
		client: client,
	}, nil
}
