// AUTOGENERATED! DO NOT EDIT.
package pizzeria

import (
	"context"
	"tonky/holistic/domain/food"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/postgres"

	"github.com/samber/do/v2"
)

type OrdererRepository interface {
    ReadOrderByID(context.Context, food.OrderID) (food.Order, error)
    SaveOrder(context.Context, NewOrder) (food.Order, error)
}

type PostgresOrderer struct {
	logger logger.SlogLogger
	client postgres.Client
}

func NewPostgresOrdererRepository(deps do.Injector) (*PostgresOrderer, error) {
	return &PostgresOrderer{
		logger: *do.MustInvoke[*logger.SlogLogger](deps),
		client: *do.MustInvoke[*postgres.Client](deps),
	}, nil
}
