// AUTOGENERATED! DO NOT EDIT.

package pizzeria

import (
	"tonky/holistic/infra/kafkaProducer"
	"tonky/holistic/infra/logger"

	"github.com/samber/do/v2"
)

type App struct {
	Deps       do.Injector
	logger     *logger.Slog

    OrdererRepo OrdererRepository
    FoodOrderCreatedProducer kafkaProducer.IFoodOrderCreated
    FoodOrderUpdatedProducer kafkaProducer.IFoodOrderUpdated
}

func NewApp(deps do.Injector) (*App, error) {
	app := App{
		Deps:       deps,
		logger:     do.MustInvoke[*logger.Slog](deps),
        OrdererRepo: do.MustInvokeAs[OrdererRepository](deps),
        FoodOrderCreatedProducer: do.MustInvokeAs[kafkaProducer.IFoodOrderCreated](deps),
        FoodOrderUpdatedProducer: do.MustInvokeAs[kafkaProducer.IFoodOrderUpdated](deps),

	}

	return &app, nil
}
