// AUTOGENERATED! DO NOT EDIT.

package legacy

import (
	"tonky/holistic/infra/logger"
)

type Deps struct {
	Config Config
	Logger *logger.Slog
    OrdererRepo OrdererRepository
    FoodOrderProducer FoodOrderProducer
}

type App struct {
	Deps       Deps
	Logger     *logger.Slog
}

func NewApp(deps Deps) (App, error) {
	app := App{
		Deps:       deps,
		Logger:     deps.Logger,
	}

	return app, nil
}
