// AUTOGENERATED! DO NOT EDIT.
package legacy

import (
	"tonky/holistic/infra/postgres"
	"tonky/holistic/infra/kafka"

	"github.com/kelseyhightower/envconfig"
)

// app specific config - infra, flags etc
type Config struct {
	Environment   string `default:"dev"`

    PostgresOrderer postgres.Config
    Kafka kafka.Config

}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("legacy", &c)
}
