// AUTOGENERATED! DO NOT EDIT.

package {{ service.Name }}

import (
	{% if service.KafkaProducers %}
	"tonky/holistic/infra/kafkaProducer"
	{% end %}
	{% if service.KafkaConsumers %}
	"tonky/holistic/infra/kafkaConsumer"
	"context"
	{% end %}
	"tonky/holistic/infra/logger"

	"github.com/samber/do/v2"
)

type App struct {
	deps       do.Injector
	logger     *logger.Slog

{% for ad in app_deps %}
    {{ ad.AppVarName() }} {{ ad.InterfaceName() }}
{% end %}
}

func NewApp(deps do.Injector) (*App, error) {
	{% if service.KafkaConsumers %}
	ctx := context.Background()

	{% end %}
	app := App{
		deps:       deps,
		logger:     do.MustInvoke[*logger.Slog](deps),
{% for ad in app_deps %}
        {{ ad.AppVarName() }}: do.MustInvokeAs[{{ ad.InterfaceName() }}](deps),
{% end %}
	}

	{% for consumer in service.KafkaConsumers %}
	go func() {
		for err := range app.{{ cap(consumer.Name) }}Consumer.Run(ctx, app.{{ cap(consumer.Name) }}Processor) {
			app.logger.Warn(err.Error())
		}
	}()
	
	{% end %}
	return &app, nil
}
