// AUTOGENERATED! DO NOT EDIT.

package {{ service_name }}

import (
	"tonky/holistic/infra/logger"

	"github.com/samber/do/v2"
)

type App struct {
	deps       do.Injector
	logger     *logger.SlogLogger

{% for i in infra %}
    {{ i.AppVarName() }} {{ i.InterfaceName() }}
{% end %}
}

func NewApp(deps do.Injector) (*App, error) {
	return &App{
		deps:       deps,
		logger:     do.MustInvoke[*logger.SlogLogger](deps),
{% for i in infra %}
        {{ i.AppVarName() }}: do.MustInvokeAs[{{ i.InterfaceName() }}](deps),
{% end %}
	}, nil
}
