// AUTOGENERATED! DO NOT EDIT.

package {{ service.Name }}

import (
	"log/slog"
	"tonky/holistic/infra/logger"
	{% if service.KafkaProducers %}
	"{{ modulePath }}/infra/kafkaProducer"
	{% end %}
	{% if service.KafkaConsumers %}
	"{{ modulePath }}/infra/kafkaConsumer"
	"context"
	{% end %}
	{% for c in service.Clients %}
	"{{ modulePath }}/clients/{{ c.Name }}"
	{% end %}
)

{% if service.Clients  %}
type Clients struct {
	{% for c in service.Clients %}
    {{ cap(c.Name) }} {{ c.Name }}.I{{ cap(c.Name) }}
	{% end %}
}
{% end %}

type Deps struct {
	Config Config
	{% for ad in app_deps %}
    {{ cap(ad.AppVarName()) }} {{ ad.InterfaceName() }}
	{% end %}
	{% for pg in service.Postgres %}
    {{ pg.Name }} I{{ pg.Name }}
	{% end %}
{% if service.Clients  %}
	Clients		Clients
{% end %}
}

type App struct {
	Deps       Deps
}

func NewApp(deps Deps) (*App, error) {
	app := App{
		Deps:       deps,
	}

	return &app, nil
}

func MustDepsFromEnv() Deps {
    slog.Debug("{{ service.Name }}.App.MustDepsFromenv()")

	cfg := MustEnvConfig()

	deps, err := DepsFromConf(cfg)
	if err != nil {
    	slog.Error("DepsFromConf error", slog.Any("config", cfg), slog.Any("err", err))
	}

	return deps
}

func DepsFromConf(cfg Config) (Deps, error) {
    slog.Debug("{{ service.Name }}.App.DepsFromConf()", slog.Any("config", cfg))

    deps := Deps{}

    {% for pg in service.Postgres %}
    {{ pg.Name}}, err := New{{ pg.Name }}(logger.Slog{}, cfg.{{ pg.Name }})
    if err != nil {
        return deps, err
    }

    deps.{{ pg.Name }} = {{ pg.Name }}
    {% end %}

    {% for ad in app_deps %}
        {% if ad.PackageName() == "local" %}
	deps.{{ cap(ad.AppVarName()) }} = app.New{{ ad.StructName() }}(l)
        {% else %}
	{{ ad.AppVarName() }}, err := {% if ad.PackageName() != "local" %}{{ ad.AppImportPackageName() }}.{% else %}app.{% end %}New{{ ad.StructName() }}(logger.Slog{}, cfg.{{ ad.ConfigVarName() }})
    if err != nil {
        return deps, err
    }
	deps.{{ cap(ad.AppVarName()) }} = {{ ad.AppVarName() }}
        {% end %}
    {% end for %}

{% if service.Clients %}
    deps.Clients = Clients{
    {% for c in service.Clients %}
        {{ cap(c.Name) }}: {{ c.Model.Package() }}.NewFromEnv(cfg.Environment),
    {% end %}
    }
{% end %}

    return deps, nil
}

{% if service.KafkaConsumers %}
func (a App) RunConsumers() {
	slog.Info("{{ service.Name}}.App.RunConsumers()")

	ctx := context.Background()
	{% for consumer in service.KafkaConsumers %}

	go func() {
		for err := range a.Deps.{{ cap(consumer.Name) }}Consumer.Run(ctx, a.{{ cap(consumer.Name) }}Processor) {
			slog.Warn(err.Error())
		}
	}()
	{% end %}
}
{% end %}