// AUTOGENERATED! DO NOT EDIT.
package {{ service.Name }}

import (
    {% for id in app_deps.Dedup() %}
    {% if id.ConfigVarName() == "Kafka" %}
	"tonky/holistic/infra/kafka"
    {% else if  id.PackageName() == "local" %}
    {% else %}
	"tonky/holistic/infra/{{ id.PackageName() }}"
    {% end %}
    {% end %}

	"github.com/kelseyhightower/envconfig"
)

// app specific config - infra, flags etc
type Config struct {
	Environment   string `default:"dev"`

    {% for id in app_deps.Dedup() %}
    {{ id.ConfigVarName() }} {{ id.ConfigVarType() }}
    {% end %}

    {% for ci in service.ConfigItems %}
    {{ ci.Model.Name }} {{ ci.Model.GoType() }} `split_words:"{{ ci.SplitWords }}"`
    {% end %}
}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("{{ service.Name }}", &c)
}
