// AUTOGENERATED! DO NOT EDIT.

package {{ service.Name }}

import (
	"{{ service.Tele.Interface.AbsPath() }}"
	{% if service.KafkaProducers %}
	"{{ modulePath }}/infra/kafkaProducer"
	{% end %}
	{% if service.KafkaConsumers %}
	"{{ modulePath }}/infra/kafkaConsumer"
	"context"
	{% end %}
	{% for c in service.Clients %}
	"{{ modulePath }}/clients/{{ c.Name }}"
	{% end %}
)

{% if service.Clients  %}
type Clients struct {
	{% for c in service.Clients %}
    {{ cap(c.Name) }} {{ c.Name }}.I{{ cap(c.Name) }}
	{% end %}
}
{% end %}

type Deps struct {
	Config Config
	// metrics
	// tracing
	{% for ad in app_deps %}
    {{ cap(ad.AppVarName()) }} {{ ad.InterfaceName() }}
	{% end %}
	{% for pg in service.Postgres %}
    {{ pg.Name }} I{{ pg.Name }}
	{% end %}
{% if service.Clients  %}
	Clients		Clients
{% end %}
}

type App struct {
	LMT {{ service.Tele.Interface.GoQualifiedModel() }}
	Deps       Deps
}

func NewApp(lmt {{ service.Tele.Interface.GoQualifiedModel() }}, deps Deps) (*App, error) {
	lmt.Logger = lmt.Logger.With("app", "{{ service.Name }}")

	app := App{
		Deps: deps,
		LMT: lmt,
	}

	return &app, nil
}

func DepsFromConf(lmt {{ service.Tele.Interface.GoQualifiedModel() }}, cfg Config) (Deps, error) {
	lmt.Logger = lmt.Logger.With("context", "app")
	lmt.Logger.Debug("DepsFromConf()", "config", cfg)

    deps := Deps{}

    {% for pg in service.Postgres %}
    {{ pg.Name}}, err := New{{ pg.Name }}(lmt, cfg.{{ pg.Name }})
    if err != nil {
        return deps, err
    }

    deps.{{ pg.Name }} = {{ pg.Name }}
    {% end %}

    {% for ad in app_deps %}
	{{ ad.AppVarName() }}, err := {% if ad.PackageName() != "local" %}{{ ad.AppImportPackageName() }}.{% else %}app.{% end %}New{{ ad.StructName() }}(lmt, cfg.{{ ad.ConfigVarName() }})
    if err != nil {
        return deps, err
    }
	deps.{{ cap(ad.AppVarName()) }} = {{ ad.AppVarName() }}
    {% end for %}

{% if service.Clients %}
    deps.Clients = Clients{
    {% for c in service.Clients %}
        {{ cap(c.Name) }}: {{ c.Model.Package() }}.NewFromEnv(),
    {% end %}
    }
{% end %}

    return deps, nil
}

{% if service.KafkaConsumers %}
func (a App) RunConsumers() {
	a.LMT.Logger.Info("RunConsumers()")

	ctx := context.Background()
	{% for consumer in service.KafkaConsumers %}

	go func() {
		for err := range a.Deps.{{ cap(consumer.Name) }}Consumer.Run(ctx, a.{{ cap(consumer.Name) }}Processor) {
			a.LMT.Logger.Error(err.Error())
		}
	}()
	{% end %}
}
{% end %}

/*
func MustDepsFromEnv() Deps {
	l := {{ service.Logger.Model.Package() }}.Default().With("app", "{{ service.Name }}")

    l.Debug("MustDepsFromenv()")

	cfg := MustEnvConfig()

	deps, err := DepsFromConf(cfg)
	if err != nil {
    	l.Error("DepsFromConf error", "config", cfg, "err", err)
	}

	return deps
}
*/