// AUTOGENERATED! DO NOT EDIT.
package {{ service.Name }}

import (
    {% for id in app_deps.Dedup() %}
    {% if id.ConfigVarName() == "Kafka" %}
	"tonky/holistic/infra/kafka"
    {% else %}
	"tonky/holistic/infra/{{ id.PackageName() }}"
    {% end %}
    {% end %}

	"github.com/kelseyhightower/envconfig"
)

// app specific config - infra, flags etc
type Config struct {
	Environment   string `default:"dev"`

    {% for id in app_deps.Dedup() %}
    {{ id.ConfigVarName() }} {{ id.ConfigVarType() }}
    {% end %}

    {% for configItem in app_config_items %}
    {{ configItem.Name }} {{ configItem.Typ }} `split_words:"true"`
    {% end %}
}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("{{ service.Name }}", &c)
}
