// AUTOGENERATED! DO NOT EDIT.
package {{ service.Name }}Client


import (
	"context"
	"log"
	"net/rpc"
	"tonky/holistic/clients"
	{% for imp in client_relative_imports %}
	{{ imp.Alias}} "tonky/holistic/{{ imp.RelPath }}"
	{% end %}
)

type I{{ cap(service.Name) }}Client interface {
{% for h in handlers %}
	{{ h.FuncName() }}(context.Context, {{ h.In.ServiceModel() }}) ({{ h.Out.ok }}, error)
{% end %}
}

func New(config clients.Config) {{ cap(service.Name) }}Client {
	return {{ cap(service.Name) }}Client{
		config: config,
	}
}

func NewFromEnv(env string) {{ cap(service.Name) }}Client {
	envConf := clients.ConfigForEnv("{{ service.Name }}", env)

	return {{ cap(service.Name) }}Client{
		config: envConf,
	}
}

type {{ cap(service.Name) }}Client struct {
	config clients.Config
}

{% for h in handlers %}
func (c {{ cap(service.Name) }}Client) {{ h.FuncName() }}(ctx context.Context, req {{ h.In.ServiceModel() }}) ({{ h.Out.ok }}, error) {
	client, err := rpc.Dial("tcp", c.config.ServerAddress())
	if err != nil {
		log.Fatal("dialing error:", err)
	}

	var reply {{ h.Out.ok }}

	err = client.Call("{{ cap(service.Name) }}.{{ h.FuncName() }}", req, &reply)
	if err != nil {
		log.Fatal("server call error:", err)
	}

	return reply, nil
}

{% end %}