// AUTOGENERATED! DO NOT EDIT.
package {{ model.Package() }}

{% if model.AbsImports(model) %}
import (
    {% for i in model.AbsImports(model) %}
    "{{ i }}"
    {% end %}
)

{% end %}
{% if model.GoType() == "struct" %}
type {{ model.Name }} struct {
    {% for field in model.Fields %}
    {{ field.GoFieldName() }} {{ field.GoStructModel(model) }}
    {% end %}
}
{% end %}
{% if model.IsBasic() or model.IsBuiltin () %}
type {{ model.Name }} {{ model.GoType() }}
{% end %}