// AUTOGENERATED! DO NOT EDIT.
package {{ service.Name}}

import (
    "context"
    "fmt"
	"net/http"
    "encoding/json"
    "log/slog"

	"github.com/go-chi/chi/v5"

	app "{{ modulePath }}/apps/{{ service.Name }}"

    {% for ci in service.AbsImports(ctx) %}
	"{{ ci }}"
    {% end %}
)

type handlers struct {
    config Config
    app app.App
    mux *chi.Mux
}

{% for h in service.Endpoints %}
func (h handlers) {{h.Name}}() http.HandlerFunc {
    return func(w http.ResponseWriter, r *http.Request) {
        var in {{ h.In.GoQualifiedModel() }}
        var out {{ h.Out.GoQualifiedModel() }}

        if err := json.NewDecoder(r.Body).Decode(&in); err != nil {
            http.Error(w, err.Error(), http.StatusBadRequest)
            return
        }

        // inDomain, dtoErr := in.ToDomain()

        out, appErr := h.app.{{h.Name}}(context.TODO(), in)

        if appErr != nil {
            http.Error(w, appErr.Error(), http.StatusBadRequest)
            return
        }

        byteResp, err := json.Marshal(out)
        if err != nil {
            http.Error(w, err.Error(), http.StatusInternalServerError)
            return
        }

        w.Write(byteResp)
    }
}

{% end %}

func NewMux(conf Config, deps app.Deps) (*chi.Mux, error) {
	a, err := app.NewApp(deps)
	if err != nil {
		panic(err)
	}

	r := chi.NewRouter()

    h := handlers{app: *a, config: conf, mux: r}

    {% for h in service.Endpoints %}
	r.Post("/{{ cap(h.Name) }}", h.{{ h.Name }}())
    {% end %}

    return r, nil
}

func NewFromEnv() (ServiceStarter, error) {
	cfg := MustEnvConfig()

    slog.Debug("{{ service.Name }}.NewFromEnv()", slog.Any("config", cfg))

    deps, err := app.DepsFromConf(cfg.App)
    if err != nil {
        return nil, err
    }

    application, appErr := app.NewApp(deps)
    if appErr != nil {
        return nil, appErr
    }

    mux, err := NewMux(cfg, deps)
    if err != nil { return nil, err}

    handlers := handlers{config: cfg, app: *application, mux: mux}

    return handlers, nil
}

func (h handlers) Config() Config {
    return h.config
}

func (h handlers) App() app.App {
    return h.app
}

func (h handlers) Start() error {
    fmt.Printf(">> {{ service.Name }}.Start() config: %+v\n", h.config)
	{% if service.KafkaConsumers %}
    h.app.RunConsumers()
    {% end %}

    return http.ListenAndServe(fmt.Sprintf(":%d", h.config.Port), h.mux)
}

func NewWithAppDeps(deps app.Deps) (ServiceStarter, error) {
	cfg := MustEnvConfig()

    slog.Debug("{{ service.Name }}.NewWithAppDeps()", slog.Any("config", cfg))

    application, appErr := app.NewApp(deps)
    if appErr != nil {
        return nil, appErr
    }

    mux, err := NewMux(cfg, deps)
    if err != nil { return nil, err}

    return handlers{config: cfg, app: *application, mux: mux}, nil
}

type ServiceStarter interface {
    Start() error
    Config() Config
    App() app.App
}
