// AUTOGENERATED! DO NOT EDIT.
package {{ service_name}}

import (
    "context"
    "fmt"
	"log"
	"net"
	"net/http"
	"net/rpc"

    // "github.com/go-playground/validator/v10"
    "github.com/samber/do/v2"

	"tonky/holistic/domain/food"
	"tonky/holistic/apps/{{ service_name }}"
)

type {{ cap(service_name) }} struct {
    config Config
    deps do.Injector
}

{% for h in handlers %}
func (h {{ cap(service_name) }}) {{h.FuncName()}}(arg {{ h.In }}, reply *{{ h.Out.ok }}) error {
    application, appErr := {{ service_name }}.NewApp(h.deps)
    if appErr != nil {
        return appErr
    }

    res, err := application.{{h.FuncName()}}(context.TODO(), arg)
    if err != nil {
        return err
    }

    *reply = res

    return nil
}

{% end %}

func New{{ cap(service_name) }}(dependencies do.Injector) ServiceStarter {
	cfg := do.MustInvoke[*Config](dependencies)

    handlers := {{ cap(service_name) }}{deps: dependencies, config: *cfg}

    return handlers
}

func (h {{ cap(service_name) }}) Start() error {
	port := h.config.Port

    fmt.Printf(">> {{ service_name }}.Start() config: %+v\n", h.config)

	rpc.Register(h)
	rpc.HandleHTTP()

	fmt.Println(">> starging server on port ", port)

	l, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
    if err != nil {
        log.Fatal("listen error:", err)
    }

    return http.Serve(l, nil)
}

type ServiceStarter interface {
    Start() error
}
