// AUTOGENERATED! DO NOT EDIT.
package {{ service_name}}

import (
    "context"
    "fmt"
	"log"
	"net"
	"net/rpc"

    // "github.com/go-playground/validator/v10"
    "github.com/samber/do/v2"

	{% for imp in service.ClientImports() %}
    {% if imp.Alias == "svc" %}
        {% continue %}
    {% end if %}
	{% if imp.Alias %}{{ imp.Alias }} {% end if %}"tonky/holistic/{{ imp.RelPath }}"
	{% end %}
	app "tonky/holistic/apps/{{ service_name }}"
)

type {{ cap(service_name) }} struct {
    config Config
    deps do.Injector
    app app.App
}

{% for h in handlers %}
func (h {{ cap(service_name) }}) {{h.FuncName()}}(arg {{ h.In }}, reply *{{ h.Out.ok }}) error {
    res, err := h.app.{{h.FuncName()}}(context.TODO(), arg{{ h.In.SvcToApp() }})
    if err != nil {
        return err
    }

    *reply = res

    return nil
}

{% end %}

func New{{ cap(service_name) }}(dependencies do.Injector) (ServiceStarter, error) {
	cfg := do.MustInvoke[*Config](dependencies)

    application, appErr := app.NewApp(dependencies)
    if appErr != nil {
        return nil, appErr
    }

    handlers := {{ cap(service_name) }}{deps: dependencies, config: *cfg, app: *application}

    return handlers, nil
}

func (h {{ cap(service_name) }}) Start() error {
	port := h.config.Port

    fmt.Printf(">> {{ service_name }}.Start() config: %+v\n", h.config)

	server := rpc.NewServer()
	server.Register(h)

	fmt.Println(">> starging server on port ", port)

	l, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
    if err != nil {
        log.Fatal("listen error:", err)
    }

	for {
		conn, err := l.Accept()
		if err != nil {
			panic(err)
		}

		go func() {
			server.ServeConn(conn)
		}()
	}
}

type ServiceStarter interface {
    Start() error
}
