// AUTOGENERATED! DO NOT EDIT.
package 

import (

	"github.com/kelseyhightower/envconfig"
)

// app specific config - infra, flags etc
type Config struct {
	Environment   string `default:"dev"`


}

func NewEnvConfig() (Config, error) {
	var c Config

	return c, envconfig.Process("", &c)
}
