// AUTOGENERATED! DO NOT EDIT.
package accounting

import (
	"context"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/postgres"
	"tonky/holistic/domain/accounting"
	"tonky/holistic/domain/food"
)

var _ OrdererRepository = new(PostgresOrderer)

type OrdererRepository interface {
    SaveFinishedOrder(context.Context, accounting.Order) (accounting.Order, error)
    ReadOrderByFoodID(context.Context, food.OrderID) (accounting.Order, error)
}

type PostgresOrderer struct {
	logger logger.Slog
	client postgres.Client
}

func NewPostgresOrderer(logger logger.Slog, conf postgres.Config) (*PostgresOrderer, error) {
	client, err := postgres.NewClient(conf)
	if err != nil {
		return nil, err
	}

	return &PostgresOrderer{
		logger: logger,
		client: client,
	}, nil
}
