// AUTOGENERATED! DO NOT EDIT.

package accounting

import (
	"tonky/holistic/infra/logger"

	"github.com/samber/do/v2"
)

type App struct {
	deps       do.Injector
	logger     *logger.Slog

}

func NewApp(deps do.Injector) (*App, error) {
	return &App{
		deps:       deps,
		logger:     do.MustInvoke[*logger.Slog](deps),
	}, nil
}
