// AUTOGENERATED! DO NOT EDIT.
package kafkaConsumer

import (
	"context"
	"encoding/json"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/kafka"

	"tonky/holistic/domain/accounting"
)

// compile-time check to make sure app-level interface is implemented
var _ IFoodOrderShipped = new(FoodOrderShipped) 

type IFoodOrderShipped interface {
	Run(context.Context, func(context.Context, accounting.OrderPrice) error) chan error
}

type FoodOrderShipped struct {
	logger logger.Slog
	client IConsumer
}

func NewFoodOrderShippedConsumer(logger logger.Slog, config kafka.Config) (*FoodOrderShipped, error) {
	client := NewConsumer(config, "food.order.shipped")

	return &FoodOrderShipped{
		logger: logger,
		client: client,
	}, nil
}

func (c FoodOrderShipped) Run(ctx context.Context, processor func(context.Context, accounting.OrderPrice) error) chan error {
	res := make(chan error)
	models, errors := ConsumeFoodOrderShipped(ctx, c.client)

	go func() {
		for {
			select {
			case model := <-models:
				c.logger.Info("kafkaConsumer.FoodOrderShipped got model", model)

				if err := processor(ctx, model); err != nil {
					res <- err
				}
			case err := <-errors:
				res <- err
			case <-ctx.Done():
				return
			}
		}
	}()

	return res
}

func ConsumeFoodOrderShipped(ctx context.Context, client IConsumer) (chan accounting.OrderPrice, chan error) {
	models := make(chan accounting.OrderPrice)
	errors := make(chan error)

	kafkaMessages, kafkaErrors := client.Consume(context.Background())

	go func() {
		for {
			select {
			case err := <-kafkaErrors:
				errors <- err
			case <-ctx.Done():
				close(models)
				return
			case msg := <-kafkaMessages:
				var model accounting.OrderPrice
				if err := json.Unmarshal(msg.Value, &model); err != nil {
					errors <- err
					continue
				}
				models <- model
			}
		}
	}()

	return models, errors
}
