// AUTOGENERATED! DO NOT EDIT.
package kafkaConsumer

import (
	"context"
	"encoding/json"
	"fmt"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/kafka"

	"tonky/holistic/domain/food"
)

// compile-time check to make sure app-level interface is implemented
var _ IFoodOrderCreated = new(FoodOrderCreated) 

type IFoodOrderCreated interface {
	Run(context.Context, func(context.Context, food.Order) error) chan error
}

type FoodOrderCreated struct {
	logger logger.Slog
	client IConsumer
}

func NewFoodOrderCreatedConsumer(logger logger.Slog, config kafka.Config) (*FoodOrderCreated, error) {
	logger.Info(">> NewFoodOrderCreatedConsumer()", "food.order.created", config.GroupID)

	client := NewConsumer(config, "food.order.created")

	return &FoodOrderCreated{
		logger: logger,
		client: client,
	}, nil
}

func (c FoodOrderCreated) Run(ctx context.Context, processor func(context.Context, food.Order) error) chan error {
	c.logger.Info(">> FoodOrderCreated.Run()", c.client.Topic())

	res := make(chan error)
	models, errors := ConsumeFoodOrderCreated(ctx, c.client)

	go func() {
		for {
			select {
			case model := <-models:
				c.logger.Info("kafkaConsumer.FoodOrderCreated got model", model)

				if err := processor(ctx, model); err != nil {
					res <- err
				}
			case err := <-errors:
				res <- err
			case <-ctx.Done():
				return
			}
		}
	}()

	return res
}

func ConsumeFoodOrderCreated(ctx context.Context, client IConsumer) (chan food.Order, chan error) {
	fmt.Println(">> ConsumeFoodOrderCreated", client.Topic())

	models := make(chan food.Order)
	errors := make(chan error)

	kafkaMessages, kafkaErrors := client.Consume(context.Background())

	go func() {
		for {
			select {
			case err := <-kafkaErrors:
				errors <- err
			case <-ctx.Done():
				close(models)
				return
			case msg := <-kafkaMessages:
				var model food.Order
				if err := json.Unmarshal(msg.Value, &model); err != nil {
					errors <- err
					continue
				}
				models <- model
			}
		}
	}()

	return models, errors
}
