// AUTOGENERATED! DO NOT EDIT.
package kafkaProducer

import (
	"context"
	"encoding/json"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/kafka"

	"tonky/holistic/domain/food"
)

// compile-time check to make sure app-level interface is implemented
var _ IFoodOrderUpdated = new(FoodOrderUpdated) 

type IFoodOrderUpdated interface {
	ProduceFoodOrderUpdated(context.Context, food.Order) error
	ProduceFoodOrderUpdatedBatch(context.Context, []food.Order) error
}

type FoodOrderUpdated struct {
	logger logger.ILogger
	client IProducer
}

func NewFoodOrderUpdatedProducer(l logger.ILogger, config kafka.Config) (*FoodOrderUpdated, error) {
	client := NewProducer(config, "food.order.updated")

	return &FoodOrderUpdated{
		logger: l,
		client: client,
	}, nil
}

func (r FoodOrderUpdated) ProduceFoodOrderUpdated(ctx context.Context, in food.Order) error {
	r.logger.Info("FoodOrderUpdated.ProduceFoodOrderUpdated", in)

	inBytes, err := json.Marshal(in)
	if err != nil {
		return err
	}

	return r.client.Produce(ctx, inBytes)
}

func (r FoodOrderUpdated) ProduceFoodOrderUpdatedBatch(ctx context.Context, ins []food.Order) error {
	r.logger.Info("FoodOrderUpdated.ProduceFoodOrderUpdatedBatch", ins)

	var data [][]byte

	for _, in  := range ins {
		inBytes, err := json.Marshal(in)
		if err != nil {
			return err
		}
	
		data = append(data, inBytes)
	}

	return r.client.ProduceBatch(ctx, data)
}
