// AUTOGENERATED! DO NOT EDIT.
package kafkaProducer

import (
	"context"
	"encoding/json"
	"tonky/holistic/infra/logger"
	"tonky/holistic/infra/kafka"

	"tonky/holistic/domain/accounting"
)

// compile-time check to make sure app-level interface is implemented
var _ IFoodOrderPaid = new(FoodOrderPaid) 

type IFoodOrderPaid interface {
	ProduceFoodOrderPaid(context.Context, accounting.Order) error
	ProduceFoodOrderPaidBatch(context.Context, []accounting.Order) error
}

type FoodOrderPaid struct {
	logger logger.Slog
	client IProducer
}

func NewFoodOrderPaid(logger logger.Slog, config kafka.Config) (*FoodOrderPaid, error) {
	client := NewProducer(config, "food.order.paid")

	return &FoodOrderPaid{
		logger: logger,
		client: client,
	}, nil
}

func (r FoodOrderPaid) ProduceFoodOrderPaid(ctx context.Context, in accounting.Order) error {
	r.logger.Info("FoodOrderPaid.ProduceFoodOrderPaid", in)

	inBytes, err := json.Marshal(in)
	if err != nil {
		return err
	}

	return r.client.Produce(ctx, inBytes)
}

func (r FoodOrderPaid) ProduceFoodOrderPaidBatch(ctx context.Context, ins []accounting.Order) error {
	r.logger.Info("FoodOrderPaid.ProduceFoodOrderPaidBatch", ins)

	var data [][]byte

	for _, in  := range ins {
		inBytes, err := json.Marshal(in)
		if err != nil {
			return err
		}
	
		data = append(data, inBytes)
	}

	return r.client.ProduceBatch(ctx, data)
}
